spring:
  output:
    ansi:
      enabled: always 

logging:
  file:
    name: log/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    com.example.basic: DEBUG
    org.hibernate: ERROR

